### ISSUE TITLE
Support InfluxDB 0.9.x+

### ISSUE THREAD

**Issue by kchristensen** [trivago/Protector#1]
Are there plans to expand InfluxDB support past 0.8? I realize the end game for this project is hopefully being replaced by functionality built into InfluxDB, but I share a lot of the same concerns and would love to vet this for use, but we're using 0.9.x.

**Comment by mre** [comment]
trivago is currently in the process of migrating to InfluxDB 0.10, so support for InfluxDB 0.9x+ is very likely. At this point in time I cannot give an ETA when it will be available.
The syntax hasn't changed that dramatically, so it shouldn't require a huge refactoring.
If you like (and if you find the time of course) you can also try to add the support yourself and send a pull request. :blush:
